name: test & lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.2.5
      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run test
